<?php

namespace Database\Factories;

use App\Models\Posting;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<\App\Models\Posting>
 */
class PostingFactory extends Factory
{
    protected $model = Posting::class;

    /**
     * Define the model's default state.
     */
    public function definition(): array
    {
        $source = $this->faker->randomElement([
            'LinkedIn',
            'Indeed',
            'Jobboom',
            'Jobillico',
            'JobBank',
            'Other',
        ]);

        $status = $this->faker->randomElement([
            'new',
            'postulated',
            'dropped',
            'rejected',
            'interview_scheduled',
            'interview_completed',
            'interview_dropped',
            'interview_rejected',
            'job_offered',
            'job_accepted',
            'job_refused',
        ]);

        $employmentType = $this->faker->randomElement(['full_time', 'part_time', 'contract', 'internship', 'temporary']);

        $workMode = $this->faker->randomElement(['in_office', 'remote', 'hybrid']);

        return [
            // id is generated by HasUuids on the model
            'source' => $source,
            'source_id' => $this->faker->unique()->bothify(
                strtoupper(substr($source, 0, 3)) . '-########'
            ),
            'employment_type' => $employmentType,
            'work_mode' => $workMode,
            'url' => $this->faker->url(),
            'company' => $this->faker->company(),
            'title' => $this->faker->jobTitle(),
            'description' => $this->faker->paragraphs(4, true),
            'status' => $status,
            'cover_letter' => $this->faker->boolean(40)
                ? $this->faker->paragraphs(3, true)
                : null,
        ];
    }

    /**
     * State: new posting.
     */
    public function asNew(): self
    {
        return $this->state(fn(array $attributes) => [
            'status' => 'new',
        ]);
    }

    /**
     * State: interview scheduled.
     */
    public function asScheduled(): self
    {
        return $this->state(fn(array $attributes) => [
            'status' => 'interview_scheduled',
        ]);
    }

    /**
     * State: rejected posting.
     */
    public function asRejected(): self
    {
        return $this->state(fn(array $attributes) => [
            'status' => 'rejected',
        ]);
    }
}
